// Mocks generated by Mockito 5.3.2 from annotations
// in auth0_flutter/example/ios/.symlinks/plugins/auth0_flutter/test/web/auth0_flutter_plugin_real_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:auth0_flutter_platform_interface/auth0_flutter_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

import 'auth0_flutter_plugin_real_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCredentials_0 extends _i1.SmartFake implements _i2.Credentials {
  _FakeCredentials_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TestPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestPlatform extends _i1.Mock implements _i3.TestPlatform {
  MockTestPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize(_i2.Account? account) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [account],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> loginWithRedirect(_i2.LoginOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithRedirect,
          [options],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i2.Credentials> credentials() => (super.noSuchMethod(
        Invocation.method(
          #credentials,
          [],
        ),
        returnValue: _i4.Future<_i2.Credentials>.value(_FakeCredentials_0(
          this,
          Invocation.method(
            #credentials,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Credentials>);
  @override
  _i4.Future<bool> hasValidCredentials() => (super.noSuchMethod(
        Invocation.method(
          #hasValidCredentials,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
