// Mocks generated by Mockito from annotations
// in auth0_flutter/example/windows/flutter/ephemeral/.plugin_symlinks/auth0_flutter/test/web/auth0_flutter_web_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:js_interop' as _i6;

import 'package:auth0_flutter/src/web/auth0_flutter_web_platform_proxy.dart'
    as _i2;
import 'package:auth0_flutter/src/web/js_interop.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [Auth0FlutterWebClientProxy].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuth0FlutterWebClientProxy extends _i1.Mock
    implements _i2.Auth0FlutterWebClientProxy {
  MockAuth0FlutterWebClientProxy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Auth0Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _i4.dummyValue<_i3.Auth0Client>(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.Auth0Client);

  @override
  _i5.Future<void> loginWithRedirect(_i3.RedirectLoginOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithRedirect,
          [options],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loginWithPopup([
    _i3.PopupLoginOptions? options,
    _i3.PopupConfigOptions? config,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithPopup,
          [
            options,
            config,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> checkSession() => (super.noSuchMethod(
        Invocation.method(
          #checkSession,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.WebCredentials> getTokenSilently(
          [_i3.GetTokenSilentlyOptions? options]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTokenSilently,
          [options],
        ),
        returnValue: _i5.Future<_i3.WebCredentials>.value(
            _i4.dummyValue<_i3.WebCredentials>(
          this,
          Invocation.method(
            #getTokenSilently,
            [options],
          ),
        )),
      ) as _i5.Future<_i3.WebCredentials>);

  @override
  _i5.Future<_i3.WebCredentials> exchangeToken(
          _i3.ExchangeTokenOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #exchangeToken,
          [options],
        ),
        returnValue: _i5.Future<_i3.WebCredentials>.value(
            _i4.dummyValue<_i3.WebCredentials>(
          this,
          Invocation.method(
            #exchangeToken,
            [options],
          ),
        )),
      ) as _i5.Future<_i3.WebCredentials>);

  @override
  _i5.Future<_i3.RedirectLoginResult> handleRedirectCallback([String? url]) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleRedirectCallback,
          [url],
        ),
        returnValue: _i5.Future<_i3.RedirectLoginResult>.value(
            _i4.dummyValue<_i3.RedirectLoginResult>(
          this,
          Invocation.method(
            #handleRedirectCallback,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.RedirectLoginResult>);

  @override
  _i5.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> logout(_i3.LogoutOptions? options) => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [options],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.JSArray<_i3.MfaAuthenticatorJS>> mfaGetAuthenticators(
          String? mfaToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #mfaGetAuthenticators,
          [mfaToken],
        ),
        returnValue: _i5.Future<_i6.JSArray<_i3.MfaAuthenticatorJS>>.value(
            _i4.dummyValue<_i6.JSArray<_i3.MfaAuthenticatorJS>>(
          this,
          Invocation.method(
            #mfaGetAuthenticators,
            [mfaToken],
          ),
        )),
      ) as _i5.Future<_i6.JSArray<_i3.MfaAuthenticatorJS>>);

  @override
  _i5.Future<_i3.MfaEnrollmentResponse> mfaEnroll(
          _i3.MfaEnrollParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #mfaEnroll,
          [params],
        ),
        returnValue: _i5.Future<_i3.MfaEnrollmentResponse>.value(
            _i4.dummyValue<_i3.MfaEnrollmentResponse>(
          this,
          Invocation.method(
            #mfaEnroll,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.MfaEnrollmentResponse>);

  @override
  _i5.Future<_i3.MfaChallengeResponse> mfaChallenge(
          _i3.MfaChallengeParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #mfaChallenge,
          [params],
        ),
        returnValue: _i5.Future<_i3.MfaChallengeResponse>.value(
            _i4.dummyValue<_i3.MfaChallengeResponse>(
          this,
          Invocation.method(
            #mfaChallenge,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.MfaChallengeResponse>);

  @override
  _i5.Future<_i3.WebCredentials> mfaVerify(_i3.MfaVerifyParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #mfaVerify,
          [params],
        ),
        returnValue: _i5.Future<_i3.WebCredentials>.value(
            _i4.dummyValue<_i3.WebCredentials>(
          this,
          Invocation.method(
            #mfaVerify,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.WebCredentials>);

  @override
  _i5.Future<_i3.PasskeyChallengeResponse> passkeyGetSignupChallenge(
          _i3.PasskeySignupChallengeParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #passkeyGetSignupChallenge,
          [params],
        ),
        returnValue: _i5.Future<_i3.PasskeyChallengeResponse>.value(
            _i4.dummyValue<_i3.PasskeyChallengeResponse>(
          this,
          Invocation.method(
            #passkeyGetSignupChallenge,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.PasskeyChallengeResponse>);

  @override
  _i5.Future<_i3.PasskeyChallengeResponse> passkeyGetLoginChallenge(
          [_i3.PasskeyLoginChallengeParams? params]) =>
      (super.noSuchMethod(
        Invocation.method(
          #passkeyGetLoginChallenge,
          [params],
        ),
        returnValue: _i5.Future<_i3.PasskeyChallengeResponse>.value(
            _i4.dummyValue<_i3.PasskeyChallengeResponse>(
          this,
          Invocation.method(
            #passkeyGetLoginChallenge,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.PasskeyChallengeResponse>);

  @override
  _i5.Future<_i3.WebCredentials> passkeyGetTokenWithPasskey(
          _i3.PasskeyGetTokenParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #passkeyGetTokenWithPasskey,
          [params],
        ),
        returnValue: _i5.Future<_i3.WebCredentials>.value(
            _i4.dummyValue<_i3.WebCredentials>(
          this,
          Invocation.method(
            #passkeyGetTokenWithPasskey,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.WebCredentials>);
}
