name: Set up iOS/macOS environment
description: Set up the environment for building and testing the library on iOS/macOS

inputs:
  platform:
    description: Either iOS or macOS
    required: true

  ruby:
    description: The version of Ruby to use
    required: true

  flutter:
    description: The version of Flutter to use
    required: true

  xcode:
    description: The version of Xcode to use
    required: true

  auth0-domain:
    description: The Auth0 domain
    required: true

  auth0-client-id:
    description: The Auth0 client ID
    required: true

runs:
  using: composite

  steps:
    - name: Lowercase platform value
      id: lowercase-platform
      run: echo "platform=$(echo ${{ inputs.platform }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Set up Ruby
      uses: ruby/setup-ruby@7886c6653556e1164c58a7603d88286b5f708293 # pin@v1.228.0
      with:
        ruby-version: ${{ inputs.ruby }}
        bundler-cache: true
        cache-version: 1
        working-directory: auth0_flutter/example/${{ steps.lowercase-platform.outputs.platform }}

    - name: Install Flutter
      uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff # pin@v2.18.0
      with:
        flutter-version: ${{ inputs.flutter }}
        channel: stable
        cache: true

    - name: Install Flutter dependencies
      working-directory: auth0_flutter/example
      run: flutter pub get
      shell: bash

    - name: Setup Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ inputs.xcode }}.app/Contents/Developer
      shell: bash

    - name: Save Xcode version
      run: xcodebuild -version | tee .xcode-version
      shell: bash

    - id: restore-pods-cache
      name: Restore Pods cache
      uses: actions/cache@v4
      with:
        path: auth0_flutter/example/${{ steps.lowercase-platform.outputs.platform }}/Pods
        key: pods-${{ hashFiles('Podfile.lock') }}-${{ hashFiles('.xcode-version') }}-v1

    - name: Install pods
      working-directory: auth0_flutter/example/${{ steps.lowercase-platform.outputs.platform }}
      run: pod install
      shell: bash

    - name: Set .env
      working-directory: auth0_flutter/example
      run: printf '%s\n%s\n%s' 'AUTH0_DOMAIN=${{ inputs.auth0-domain }}' 'AUTH0_CLIENT_ID=${{ inputs.auth0-client-id }}' 'AUTH0_CUSTOM_SCHEME=demo' >> .env
      shell: bash
