name: Run iOS/macOS smoke tests
description: Execute the smoke test suite on iOS/macOS

inputs:
  platform:
    description: Either iOS or macOS
    required: true

  destination:
    description: The destination string for xcodebuild
    required: true

runs:
  using: composite

  steps:
    - name: Lowercase platform value
      id: lowercase-platform
      run: echo "platform=$(echo ${{ inputs.platform }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Build ${{ inputs.platform }} app
      working-directory: auth0_flutter/example
      run: flutter build ${{ steps.lowercase-platform.outputs.platform }} --debug ${{ inputs.platform == 'iOS' && '--no-codesign' || '' }}
      shell: bash

    - name: Disable iOS hardware keyboard
      if: ${{ inputs.platform == 'iOS' }}
      run: defaults write com.apple.iphonesimulator ConnectHardwareKeyboard 0
      shell: bash

    - name: Run ${{ inputs.platform }} smoke tests
      working-directory: auth0_flutter/example/${{ steps.lowercase-platform.outputs.platform }}
      run: xcodebuild test -scheme Runner -workspace Runner.xcworkspace -destination '${{ inputs.destination }}' -resultBundlePath smoke-tests.xcresult -only-testing:RunnerUITests
      shell: bash

    - name: Upload xcresult bundles
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: "${{ inputs.platform }} xcresult bundles (smoke tests)"
        path: "auth0_flutter/example/${{ steps.lowercase-platform.outputs.platform }}/smoke-tests.xcresult"
