blank_issues_enabled: false
contact_links:
  - name: 🤔 Help & Questions
    url: https://community.auth0.com/c/sdks/5
    about: Ask general support or usage questions in the Auth0 Community forums.
  - name: 📑 FAQ
    url: https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md
    about: Check some commonly asked questions.
  - name: 📖 API Documentation
    url: https://pub.dev/documentation/auth0_flutter/latest/
    about: Check the public API documentation for in-depth overview of all the available features.
