name: Set up Flutter and Dart SDK for publishing
description: Set up the environment for publishing the Flutter libraries to pub.dev

inputs:
  flutter:
    description: The version of Flutter to use
    required: true

  working-directory:
    description: The directory of the package to publish
    required: true

runs:
  using: composite

  steps:
    - name: Install Flutter
      uses: subosito/flutter-action@395322a6cded4e9ed503aebd4cc1965625f8e59a # pin@v2.20.0
      with:
        flutter-version: ${{ inputs.flutter }}
        channel: stable
        cache: true

    - name: Install Flutter dependencies
      working-directory: ${{ inputs.working-directory }}
      run: flutter pub get
      shell: bash

    - name: Setup Dart SDK for publishing # With JWT token
      uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # pin@v1.7.1
