name: Set up Android environment
description: Set up the environment for building and testing the library on Android

inputs:
  flutter:
    description: The version of Flutter to use
    required: true

  java:
    description: The version of Java to use
    required: true

  auth0-domain:
    description: The Auth0 domain
    required: true

  auth0-client-id:
    description: The Auth0 client ID
    required: true

runs:
  using: composite

  steps:
    - name: Install Flutter
      uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e  #pin@v2.21.0
      with:
        flutter-version: 3.29.3
        channel: stable
        cache: true

    - name: Install Flutter dependencies
      working-directory: auth0_flutter/example
      run: flutter pub get
      shell: bash

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java }}
        cache: 'gradle'

    - name: Read Gradle version from gradle.properties
      id: gradle-version
      working-directory: auth0_flutter/example/android
      run: |
        if [ ! -f "gradle/wrapper/gradle-wrapper.properties" ]; then
          echo "ERROR: gradle-wrapper.properties file not found!"
          exit 1
        fi

        # Reading gradle-wrapper.properties
        cat gradle/wrapper/gradle-wrapper.properties

        # Extract Gradle version from distributionUrl
        GRADLE_VERSION=$(grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties | sed -n 's/.*gradle-\([0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?\).*/\1/p')

        if [ -z "$GRADLE_VERSION" ]; then
          echo "ERROR: Could not extract Gradle version from gradle-wrapper.properties"
          echo "Please check the distributionUrl format in gradle/wrapper/gradle-wrapper.properties"
          exit 1
        fi

        echo "Extracted Gradle version: $GRADLE_VERSION"
        echo "gradle-version=$GRADLE_VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
          gradle-version: ${{ steps.gradle-version.outputs.gradle-version }}

    - name: Set .env
      working-directory: auth0_flutter/example
      run: printf '%s\n%s\n%s' 'AUTH0_DOMAIN=${{ inputs.auth0-domain }}' 'AUTH0_CLIENT_ID=${{ inputs.auth0-client-id }}' 'AUTH0_CUSTOM_SCHEME=demo' >> .env
      shell: bash

    - name: Set strings.xml
      working-directory: auth0_flutter/example/android/app/src/main/res/values
      run: |
        mv strings.xml.example strings.xml
        sed -r -i.bak 's/YOUR_AUTH0_DOMAIN/${{ inputs.auth0-domain }}/' strings.xml
        rm strings.xml.bak
      shell: bash

    - name: Set Gradle wrapper
      working-directory: auth0_flutter/example/android
      run: |
        gradle wrapper --gradle-version ${{ steps.gradle-version.outputs.gradle-version }} --distribution-type bin
        chmod +x gradlew
      shell: bash
