// Mocks generated by Mockito 5.1.0 from annotations
// in auth0_flutter/test/credentials_manager_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:auth0_flutter/auth0_flutter.dart' as _i2;
import 'package:auth0_flutter_platform_interface/auth0_flutter_platform_interface.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

import 'credentials_manager_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCredentials_0 extends _i1.Fake implements _i2.Credentials {}

/// A class which mocks [TestPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestPlatform extends _i1.Mock implements _i3.TestPlatform {
  MockTestPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Credentials> getCredentials(
          _i5.CredentialsManagerRequest<_i5.GetCredentialsOptions>? request) =>
      (super.noSuchMethod(Invocation.method(#getCredentials, [request]),
              returnValue: Future<_i2.Credentials>.value(_FakeCredentials_0()))
          as _i4.Future<_i2.Credentials>);
  @override
  _i4.Future<void> clearCredentials(
          _i5.CredentialsManagerRequest<_i5.RequestOptions?>? request) =>
      (super.noSuchMethod(Invocation.method(#clearCredentials, [request]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> saveCredentials(
          _i5.CredentialsManagerRequest<_i5.SaveCredentialsOptions>? request) =>
      (super.noSuchMethod(Invocation.method(#saveCredentials, [request]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<bool> hasValidCredentials(
          _i5.CredentialsManagerRequest<_i5.HasValidCredentialsOptions>?
              request) =>
      (super.noSuchMethod(Invocation.method(#hasValidCredentials, [request]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}
