// Mocks generated by Mockito 5.4.5 from annotations
// in auth0_flutter/example/windows/flutter/ephemeral/.plugin_symlinks/auth0_flutter/test/mobile/mfa_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:auth0_flutter/auth0_flutter.dart' as _i2;
import 'package:auth0_flutter_platform_interface/auth0_flutter_platform_interface.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

import 'mfa_api_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMfaEnrollmentChallenge_0 extends _i1.SmartFake
    implements _i2.MfaEnrollmentChallenge {
  _FakeMfaEnrollmentChallenge_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMfaChallenge_1 extends _i1.SmartFake implements _i2.MfaChallenge {
  _FakeMfaChallenge_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCredentials_2 extends _i1.SmartFake implements _i2.Credentials {
  _FakeCredentials_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TestPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestPlatform extends _i1.Mock implements _i3.TestPlatform {
  MockTestPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.MfaAuthenticator>> getAuthenticators(
    _i5.ApiRequest<_i5.MfaGetAuthenticatorsOptions>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAuthenticators, [request]),
            returnValue: _i4.Future<List<_i2.MfaAuthenticator>>.value(
              <_i2.MfaAuthenticator>[],
            ),
          )
          as _i4.Future<List<_i2.MfaAuthenticator>>);

  @override
  _i4.Future<_i2.MfaEnrollmentChallenge> enrollTotp(
    _i5.ApiRequest<_i5.MfaEnrollTotpOptions>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enrollTotp, [request]),
            returnValue: _i4.Future<_i2.MfaEnrollmentChallenge>.value(
              _FakeMfaEnrollmentChallenge_0(
                this,
                Invocation.method(#enrollTotp, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.MfaEnrollmentChallenge>);

  @override
  _i4.Future<_i2.MfaEnrollmentChallenge> enrollPhone(
    _i5.ApiRequest<_i5.MfaEnrollPhoneOptions>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enrollPhone, [request]),
            returnValue: _i4.Future<_i2.MfaEnrollmentChallenge>.value(
              _FakeMfaEnrollmentChallenge_0(
                this,
                Invocation.method(#enrollPhone, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.MfaEnrollmentChallenge>);

  @override
  _i4.Future<_i2.MfaEnrollmentChallenge> enrollEmail(
    _i5.ApiRequest<_i5.MfaEnrollEmailOptions>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enrollEmail, [request]),
            returnValue: _i4.Future<_i2.MfaEnrollmentChallenge>.value(
              _FakeMfaEnrollmentChallenge_0(
                this,
                Invocation.method(#enrollEmail, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.MfaEnrollmentChallenge>);

  @override
  _i4.Future<_i2.MfaEnrollmentChallenge> enrollPush(
    _i5.ApiRequest<_i5.MfaEnrollPushOptions>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enrollPush, [request]),
            returnValue: _i4.Future<_i2.MfaEnrollmentChallenge>.value(
              _FakeMfaEnrollmentChallenge_0(
                this,
                Invocation.method(#enrollPush, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.MfaEnrollmentChallenge>);

  @override
  _i4.Future<_i2.MfaChallenge> challenge(
    _i5.ApiRequest<_i5.MfaChallengeOptions>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#challenge, [request]),
            returnValue: _i4.Future<_i2.MfaChallenge>.value(
              _FakeMfaChallenge_1(
                this,
                Invocation.method(#challenge, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.MfaChallenge>);

  @override
  _i4.Future<_i2.Credentials> verify(
    _i5.ApiRequest<_i5.MfaVerifyOptions>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verify, [request]),
            returnValue: _i4.Future<_i2.Credentials>.value(
              _FakeCredentials_2(this, Invocation.method(#verify, [request])),
            ),
          )
          as _i4.Future<_i2.Credentials>);
}
