// Mocks generated by Mockito 5.4.6 from annotations
// in auth0_flutter/test/mobile/passwordless_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:auth0_flutter/auth0_flutter.dart' as _i2;
import 'package:auth0_flutter_platform_interface/auth0_flutter_platform_interface.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

import 'passwordless_api_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCredentials_0 extends _i1.SmartFake implements _i2.Credentials {
  _FakeCredentials_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_1 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseUser_2 extends _i1.SmartFake implements _i2.DatabaseUser {
  _FakeDatabaseUser_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSSOCredentials_3 extends _i1.SmartFake
    implements _i2.SSOCredentials {
  _FakeSSOCredentials_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePasskeyChallenge_4 extends _i1.SmartFake
    implements _i2.PasskeyChallenge {
  _FakePasskeyChallenge_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePasswordlessChallenge_5 extends _i1.SmartFake
    implements _i2.PasswordlessChallenge {
  _FakePasswordlessChallenge_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TestPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestPlatform extends _i1.Mock implements _i3.TestPlatform {
  MockTestPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Credentials> login(
          _i5.ApiRequest<_i5.AuthLoginOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue: _i4.Future<_i2.Credentials>.value(_FakeCredentials_0(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Credentials>);

  @override
  _i4.Future<void> startPasswordlessWithEmail(
          _i5.ApiRequest<_i5.AuthPasswordlessLoginOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #startPasswordlessWithEmail,
          [request],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Credentials> loginWithEmailCode(
          _i5.ApiRequest<_i5.AuthLoginWithCodeOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithEmailCode,
          [request],
        ),
        returnValue: _i4.Future<_i2.Credentials>.value(_FakeCredentials_0(
          this,
          Invocation.method(
            #loginWithEmailCode,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Credentials>);

  @override
  _i4.Future<void> startPasswordlessWithPhoneNumber(
          _i5.ApiRequest<_i5.AuthPasswordlessLoginOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #startPasswordlessWithPhoneNumber,
          [request],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Credentials> loginWithSmsCode(
          _i5.ApiRequest<_i5.AuthLoginWithCodeOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithSmsCode,
          [request],
        ),
        returnValue: _i4.Future<_i2.Credentials>.value(_FakeCredentials_0(
          this,
          Invocation.method(
            #loginWithSmsCode,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Credentials>);

  @override
  _i4.Future<_i2.UserProfile> userInfo(
          _i5.ApiRequest<_i5.AuthUserInfoOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #userInfo,
          [request],
        ),
        returnValue: _i4.Future<_i2.UserProfile>.value(_FakeUserProfile_1(
          this,
          Invocation.method(
            #userInfo,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.UserProfile>);

  @override
  _i4.Future<_i2.DatabaseUser> signup(
          _i5.ApiRequest<_i5.AuthSignupOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [request],
        ),
        returnValue: _i4.Future<_i2.DatabaseUser>.value(_FakeDatabaseUser_2(
          this,
          Invocation.method(
            #signup,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.DatabaseUser>);

  @override
  _i4.Future<_i2.Credentials> renew(
          _i5.ApiRequest<_i5.AuthRenewOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #renew,
          [request],
        ),
        returnValue: _i4.Future<_i2.Credentials>.value(_FakeCredentials_0(
          this,
          Invocation.method(
            #renew,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Credentials>);

  @override
  _i4.Future<_i2.Credentials> customTokenExchange(
          _i5.ApiRequest<_i5.AuthCustomTokenExchangeOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #customTokenExchange,
          [request],
        ),
        returnValue: _i4.Future<_i2.Credentials>.value(_FakeCredentials_0(
          this,
          Invocation.method(
            #customTokenExchange,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Credentials>);

  @override
  _i4.Future<_i2.SSOCredentials> ssoExchange(
          _i5.ApiRequest<_i5.AuthSSOExchangeOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #ssoExchange,
          [request],
        ),
        returnValue: _i4.Future<_i2.SSOCredentials>.value(_FakeSSOCredentials_3(
          this,
          Invocation.method(
            #ssoExchange,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.SSOCredentials>);

  @override
  _i4.Future<void> resetPassword(
          _i5.ApiRequest<_i5.AuthResetPasswordOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.PasskeyChallenge> passkeyLoginChallenge(
          _i5.ApiRequest<_i5.AuthPasskeyLoginChallengeOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #passkeyLoginChallenge,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.PasskeyChallenge>.value(_FakePasskeyChallenge_4(
          this,
          Invocation.method(
            #passkeyLoginChallenge,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.PasskeyChallenge>);

  @override
  _i4.Future<_i2.PasskeyChallenge> passkeySignupChallenge(
          _i5.ApiRequest<_i5.AuthPasskeySignupChallengeOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #passkeySignupChallenge,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.PasskeyChallenge>.value(_FakePasskeyChallenge_4(
          this,
          Invocation.method(
            #passkeySignupChallenge,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.PasskeyChallenge>);

  @override
  _i4.Future<_i2.Credentials> passkeyCredentialExchange(
          _i5.ApiRequest<_i5.AuthPasskeyExchangeOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #passkeyCredentialExchange,
          [request],
        ),
        returnValue: _i4.Future<_i2.Credentials>.value(_FakeCredentials_0(
          this,
          Invocation.method(
            #passkeyCredentialExchange,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Credentials>);

  @override
  _i4.Future<_i2.PasswordlessChallenge> passwordlessChallengeWithEmail(
          _i5.ApiRequest<_i5.AuthPasswordlessChallengeEmailOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #passwordlessChallengeWithEmail,
          [request],
        ),
        returnValue: _i4.Future<_i2.PasswordlessChallenge>.value(
            _FakePasswordlessChallenge_5(
          this,
          Invocation.method(
            #passwordlessChallengeWithEmail,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.PasswordlessChallenge>);

  @override
  _i4.Future<_i2.PasswordlessChallenge> passwordlessChallengeWithPhoneNumber(
          _i5.ApiRequest<_i5.AuthPasswordlessChallengePhoneOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #passwordlessChallengeWithPhoneNumber,
          [request],
        ),
        returnValue: _i4.Future<_i2.PasswordlessChallenge>.value(
            _FakePasswordlessChallenge_5(
          this,
          Invocation.method(
            #passwordlessChallengeWithPhoneNumber,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.PasswordlessChallenge>);

  @override
  _i4.Future<_i2.Credentials> passwordlessLoginWithOtp(
          _i5.ApiRequest<_i5.AuthPasswordlessLoginWithOtpOptions>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #passwordlessLoginWithOtp,
          [request],
        ),
        returnValue: _i4.Future<_i2.Credentials>.value(_FakeCredentials_0(
          this,
          Invocation.method(
            #passwordlessLoginWithOtp,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Credentials>);
}
