name: Publish auth0_flutter_platform_interface to pub.dev

on:
  push:
    branches:
      - 'reversing_labs'
#    tags:
#      - 'afpi-v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write
  id-token: write

env:
  flutter: '3.x'

jobs:
  rl-scanner:
    uses: ./.github/workflows/rl-scanner.yml
    with:
      flutter: ${{ env.flutter }}
      artifact-name: 'flutter-auth0-package.zip'
    secrets:
      RLSECURE_LICENSE: ${{ secrets.RLSECURE_LICENSE }}
      RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
      SIGNAL_HANDLER_TOKEN: ${{ secrets.SIGNAL_HANDLER_TOKEN }}
      PRODSEC_TOOLS_USER: ${{ secrets.PRODSEC_TOOLS_USER }}
      PRODSEC_TOOLS_TOKEN: ${{ secrets.PRODSEC_TOOLS_TOKEN }}
      PRODSEC_TOOLS_ARN: ${{ secrets.PRODSEC_TOOLS_ARN }}

  publish:
    name: Publish auth0_flutter_platform_interface to pub.dev
    environment: ${{ github.event.pull_request.head.repo.fork && 'external' || 'internal' }}
    needs: rl-scanner
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup Flutter and Dart SDK
        uses: ./.github/actions/setup-publish
        with:
          flutter: ${{ env.flutter }}
          working-directory: auth0_flutter_platform_interface

      - name: Publish
        run: dart pub publish -f
        working-directory: auth0_flutter_platform_interface
