name: Publish auth0_flutter to pub.dev

on:
  push:
    tags:
      - 'af-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: auth0_flutter
