
name: RL-Security-Scanner
run-name: rl-security-scanner


on:
  merge_group:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checkout-build-scan-only:
    if: github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request')
      # && startsWith(github.event.pull_request.head.ref, 'release/'))
    runs-on: ubuntu-latest


    permissions:
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225
        with:
          flutter-version: ${{ env.flutter }}
          channel: stable
          cache: true

      - name: Add example/.env
        working-directory: auth0_flutter
        run: cp example/.env.example example/.env

      - name: Install dependencies
        working-directory: auth0_flutter
        run: flutter pub get

      - name: Analyze
        working-directory: auth0_flutter
        run: flutter analyze

      - name: Build package
        shell: bash
        run: |
           zip -r flutter-auth0-package.zip auth0_flutter auth0_flutter_platform_interface codecov.yml README.md LICENSE

      - name: Get Artifact Version
        id: get_version
        run: |
          version=$(cat .version)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Output build artifact
        id: output_build_artifact
        run: |
          echo "scanfile=$(ls flutter-auth0-package.zip)" >> $GITHUB_OUTPUT


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install boto3 requests
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.PRODSEC_TOOLS_ARN }}
          aws-region: us-east-1
          mask-aws-account-id: true

      - name: Run Reversing Labs Wrapper Scanner
        env:
          RLSECURE_LICENSE: ${{ secrets.RLSECURE_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
          SIGNAL_HANDLER_TOKEN: ${{ secrets.SIGNAL_HANDLER_TOKEN }}
          WRAPPER_INDEX_URL: "https://${{ secrets.PRODSEC_TOOLS_USER }}:${{ secrets.PRODSEC_TOOLS_TOKEN }}@a0us.jfrog.io/artifactory/api/pypi/python-local/simple"
          PYTHONUNBUFFERED: 1
        run: |
          pip install rl-wrapper --index-url "$WRAPPER_INDEX_URL" && \
          rl-wrapper \
            --artifact "${{ steps.output_build_artifact.outputs.scanfile }}" \
            --version "${{ steps.get_version.outputs.version }}" \
            --name "${{ github.event.repository.name }}" \
            --repository "${{ github.repository }}" \
            --commit "${{ github.sha }}" \
            --build-env "github_actions" \
            --suppress_output
        continue-on-error: true
